//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_TienNghi
    {
        public string MaCTTN { get; set; }
        public string SoPhong { get; set; }
        public string MaTN { get; set; }
        public Nullable<int> SL { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual TienNghi TienNghi { get; set; }
    }
}
