//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CT_TienNghi : INotifyPropertyChanged
    {
        public int MaCTTN { get; set; }

        private string soPhong;
        private int? maTN;
        private int sl;
        public string SoPhong 
        {
            get => soPhong;
            set
            {
                soPhong = value;
                OnPropertyChanged("SoPhong");
            }
        }
        public Nullable<int> MaTN
        {
            get => maTN;
            set
            {
                maTN = value;
                OnPropertyChanged("MaTN");
            }
        }
        public int SL 
        {
            get => sl;
            set
            {
                sl = value;
                OnPropertyChanged("SL");
            }
        }
    
        public virtual Phong Phong { get; set; }
        public virtual TienNghi TienNghi { get; set; }
        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string newName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(newName));
            }
        }
    }
}
