//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> MaCTPT { get; set; }
    
        public virtual CT_PhieuThue CT_PhieuThue { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
